// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1216109504;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__keeper__cancel_enrollment_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_enrollment",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::cancel_enrollment())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__keeper__close_timeout_ms_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_timeout_ms",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_kind = <Option<crate::api::keeper::CommandKind>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::close_timeout_ms(api_kind))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__keeper__color_seeds_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "color_seeds",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::color_seeds())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__keeper__default_color_seed_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "default_color_seed",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::default_color_seed())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__keeper__dispatch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dispatch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_command = <crate::api::keeper::Command>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::keeper::CommandError>((move || {
                    let output_ok = crate::api::keeper::dispatch(api_command)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__keeper__enroll_captured_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "enroll_captured",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::enroll_captured())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__keeper__fingerprint_name_max_bytes_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fingerprint_name_max_bytes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::fingerprint_name_max_bytes())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::simple::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__keeper__operation_inputs_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "operation_inputs",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_kind = <crate::api::keeper::CommandKind>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::operation_inputs(api_kind))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__models__preferences_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "preferences_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::models::Preferences::default())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__keeper__supported_locales_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "supported_locales",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::keeper::supported_locales())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::models::BioTemplateSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        return crate::api::models::BioTemplateSummary {
            id: var_id,
            name: var_name,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::keeper::Command {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::keeper::CommandKind>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        let mut var_pin = <String>::sse_decode(deserializer);
        let mut var_newPin = <String>::sse_decode(deserializer);
        let mut var_confirmPin = <String>::sse_decode(deserializer);
        let mut var_confirmed = <bool>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        return crate::api::keeper::Command {
            kind: var_kind,
            value: var_value,
            pin: var_pin,
            new_pin: var_newPin,
            confirm_pin: var_confirmPin,
            confirmed: var_confirmed,
            name: var_name,
        };
    }
}

impl SseDecode for crate::api::keeper::CommandError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_cancelled = <bool>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::keeper::CommandError {
            cancelled: var_cancelled,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::keeper::CommandKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::keeper::CommandKind::Initialize,
            1 => crate::api::keeper::CommandKind::EnterFingerprints,
            2 => crate::api::keeper::CommandKind::Load,
            3 => crate::api::keeper::CommandKind::Scan,
            4 => crate::api::keeper::CommandKind::Connect,
            5 => crate::api::keeper::CommandKind::Disconnect,
            6 => crate::api::keeper::CommandKind::Hide,
            7 => crate::api::keeper::CommandKind::Unhide,
            8 => crate::api::keeper::CommandKind::ListCredentials,
            9 => crate::api::keeper::CommandKind::DeleteCredential,
            10 => crate::api::keeper::CommandKind::ChangePin,
            11 => crate::api::keeper::CommandKind::ListBio,
            12 => crate::api::keeper::CommandKind::EnrollBio,
            13 => crate::api::keeper::CommandKind::DeleteBio,
            14 => crate::api::keeper::CommandKind::RenameBio,
            15 => crate::api::keeper::CommandKind::Reset,
            16 => crate::api::keeper::CommandKind::Filter,
            17 => crate::api::keeper::CommandKind::Theme,
            18 => crate::api::keeper::CommandKind::Locale,
            19 => crate::api::keeper::CommandKind::Shutdown,
            20 => crate::api::keeper::CommandKind::DynamicColor,
            21 => crate::api::keeper::CommandKind::ColorSeed,
            _ => unreachable!("Invalid variant for CommandKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::models::CredentialSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_rpId = <String>::sse_decode(deserializer);
        let mut var_rpName = <String>::sse_decode(deserializer);
        let mut var_userName = <String>::sse_decode(deserializer);
        let mut var_userDisplayName = <String>::sse_decode(deserializer);
        return crate::api::models::CredentialSummary {
            id: var_id,
            rp_id: var_rpId,
            rp_name: var_rpName,
            user_name: var_userName,
            user_display_name: var_userDisplayName,
        };
    }
}

impl SseDecode for crate::api::models::DeviceSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_transport = <crate::api::models::Transport>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_protocol = <String>::sse_decode(deserializer);
        let mut var_credentialManagement = <bool>::sse_decode(deserializer);
        let mut var_pin = <bool>::sse_decode(deserializer);
        let mut var_fingerprint = <bool>::sse_decode(deserializer);
        return crate::api::models::DeviceSummary {
            transport: var_transport,
            path: var_path,
            label: var_label,
            protocol: var_protocol,
            credential_management: var_credentialManagement,
            pin: var_pin,
            fingerprint: var_fingerprint,
        };
    }
}

impl SseDecode for crate::api::models::HiddenAuthenticator {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        return crate::api::models::HiddenAuthenticator {
            path: var_path,
            label: var_label,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::BioTemplateSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::BioTemplateSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::CredentialSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::CredentialSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::DeviceSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::DeviceSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::models::HiddenAuthenticator> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::models::HiddenAuthenticator>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::keeper::OperationInputs {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_askPin = <bool>::sse_decode(deserializer);
        let mut var_changePin = <bool>::sse_decode(deserializer);
        let mut var_requiresConfirmation = <bool>::sse_decode(deserializer);
        let mut var_touchesHardware = <bool>::sse_decode(deserializer);
        let mut var_mutatesDevice = <bool>::sse_decode(deserializer);
        return crate::api::keeper::OperationInputs {
            ask_pin: var_askPin,
            change_pin: var_changePin,
            requires_confirmation: var_requiresConfirmation,
            touches_hardware: var_touchesHardware,
            mutates_device: var_mutatesDevice,
        };
    }
}

impl SseDecode for Option<crate::api::keeper::CommandKind> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::keeper::CommandKind>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::models::DeviceSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::models::DeviceSummary>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::models::Preferences {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_locale = <String>::sse_decode(deserializer);
        let mut var_theme = <String>::sse_decode(deserializer);
        let mut var_hiddenAuthenticators =
            <Vec<crate::api::models::HiddenAuthenticator>>::sse_decode(deserializer);
        let mut var_dynamicColor = <bool>::sse_decode(deserializer);
        let mut var_colorSeed = <String>::sse_decode(deserializer);
        return crate::api::models::Preferences {
            locale: var_locale,
            theme: var_theme,
            hidden_authenticators: var_hiddenAuthenticators,
            dynamic_color: var_dynamicColor,
            color_seed: var_colorSeed,
        };
    }
}

impl SseDecode for crate::api::keeper::Snapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_canManageCredentials = <bool>::sse_decode(deserializer);
        let mut var_canManageFingerprints = <bool>::sse_decode(deserializer);
        let mut var_devices = <Vec<crate::api::models::DeviceSummary>>::sse_decode(deserializer);
        let mut var_active = <Option<crate::api::models::DeviceSummary>>::sse_decode(deserializer);
        let mut var_credentials =
            <Vec<crate::api::models::CredentialSummary>>::sse_decode(deserializer);
        let mut var_existing = <u64>::sse_decode(deserializer);
        let mut var_remaining = <u64>::sse_decode(deserializer);
        let mut var_templates =
            <Vec<crate::api::models::BioTemplateSummary>>::sse_decode(deserializer);
        let mut var_preferences = <crate::api::models::Preferences>::sse_decode(deserializer);
        let mut var_query = <String>::sse_decode(deserializer);
        let mut var_credentialsLoaded = <bool>::sse_decode(deserializer);
        let mut var_fingerprintsLoaded = <bool>::sse_decode(deserializer);
        return crate::api::keeper::Snapshot {
            can_manage_credentials: var_canManageCredentials,
            can_manage_fingerprints: var_canManageFingerprints,
            devices: var_devices,
            active: var_active,
            credentials: var_credentials,
            existing: var_existing,
            remaining: var_remaining,
            templates: var_templates,
            preferences: var_preferences,
            query: var_query,
            credentials_loaded: var_credentialsLoaded,
            fingerprints_loaded: var_fingerprintsLoaded,
        };
    }
}

impl SseDecode for crate::api::models::Transport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::models::Transport::Usb,
            1 => crate::api::models::Transport::Nfc,
            2 => crate::api::models::Transport::Hid,
            _ => unreachable!("Invalid variant for Transport: {}", inner),
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        5 => wire__crate__api__keeper__dispatch_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__models__preferences_default_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__keeper__cancel_enrollment_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__keeper__close_timeout_ms_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__keeper__color_seeds_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__keeper__default_color_seed_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__keeper__enroll_captured_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__keeper__fingerprint_name_max_bytes_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__keeper__operation_inputs_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__keeper__supported_locales_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::BioTemplateSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::BioTemplateSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::BioTemplateSummary>
    for crate::api::models::BioTemplateSummary
{
    fn into_into_dart(self) -> crate::api::models::BioTemplateSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::keeper::Command {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.pin.into_into_dart().into_dart(),
            self.new_pin.into_into_dart().into_dart(),
            self.confirm_pin.into_into_dart().into_dart(),
            self.confirmed.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::keeper::Command {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::keeper::Command>
    for crate::api::keeper::Command
{
    fn into_into_dart(self) -> crate::api::keeper::Command {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::keeper::CommandError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.cancelled.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::keeper::CommandError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::keeper::CommandError>
    for crate::api::keeper::CommandError
{
    fn into_into_dart(self) -> crate::api::keeper::CommandError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::keeper::CommandKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Initialize => 0.into_dart(),
            Self::EnterFingerprints => 1.into_dart(),
            Self::Load => 2.into_dart(),
            Self::Scan => 3.into_dart(),
            Self::Connect => 4.into_dart(),
            Self::Disconnect => 5.into_dart(),
            Self::Hide => 6.into_dart(),
            Self::Unhide => 7.into_dart(),
            Self::ListCredentials => 8.into_dart(),
            Self::DeleteCredential => 9.into_dart(),
            Self::ChangePin => 10.into_dart(),
            Self::ListBio => 11.into_dart(),
            Self::EnrollBio => 12.into_dart(),
            Self::DeleteBio => 13.into_dart(),
            Self::RenameBio => 14.into_dart(),
            Self::Reset => 15.into_dart(),
            Self::Filter => 16.into_dart(),
            Self::Theme => 17.into_dart(),
            Self::Locale => 18.into_dart(),
            Self::Shutdown => 19.into_dart(),
            Self::DynamicColor => 20.into_dart(),
            Self::ColorSeed => 21.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::keeper::CommandKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::keeper::CommandKind>
    for crate::api::keeper::CommandKind
{
    fn into_into_dart(self) -> crate::api::keeper::CommandKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::CredentialSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.rp_id.into_into_dart().into_dart(),
            self.rp_name.into_into_dart().into_dart(),
            self.user_name.into_into_dart().into_dart(),
            self.user_display_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::CredentialSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::CredentialSummary>
    for crate::api::models::CredentialSummary
{
    fn into_into_dart(self) -> crate::api::models::CredentialSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::DeviceSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.transport.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.protocol.into_into_dart().into_dart(),
            self.credential_management.into_into_dart().into_dart(),
            self.pin.into_into_dart().into_dart(),
            self.fingerprint.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::DeviceSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::DeviceSummary>
    for crate::api::models::DeviceSummary
{
    fn into_into_dart(self) -> crate::api::models::DeviceSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::HiddenAuthenticator {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::HiddenAuthenticator
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::HiddenAuthenticator>
    for crate::api::models::HiddenAuthenticator
{
    fn into_into_dart(self) -> crate::api::models::HiddenAuthenticator {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::keeper::OperationInputs {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ask_pin.into_into_dart().into_dart(),
            self.change_pin.into_into_dart().into_dart(),
            self.requires_confirmation.into_into_dart().into_dart(),
            self.touches_hardware.into_into_dart().into_dart(),
            self.mutates_device.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::keeper::OperationInputs
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::keeper::OperationInputs>
    for crate::api::keeper::OperationInputs
{
    fn into_into_dart(self) -> crate::api::keeper::OperationInputs {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::Preferences {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.locale.into_into_dart().into_dart(),
            self.theme.into_into_dart().into_dart(),
            self.hidden_authenticators.into_into_dart().into_dart(),
            self.dynamic_color.into_into_dart().into_dart(),
            self.color_seed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::models::Preferences
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::Preferences>
    for crate::api::models::Preferences
{
    fn into_into_dart(self) -> crate::api::models::Preferences {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::keeper::Snapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.can_manage_credentials.into_into_dart().into_dart(),
            self.can_manage_fingerprints.into_into_dart().into_dart(),
            self.devices.into_into_dart().into_dart(),
            self.active.into_into_dart().into_dart(),
            self.credentials.into_into_dart().into_dart(),
            self.existing.into_into_dart().into_dart(),
            self.remaining.into_into_dart().into_dart(),
            self.templates.into_into_dart().into_dart(),
            self.preferences.into_into_dart().into_dart(),
            self.query.into_into_dart().into_dart(),
            self.credentials_loaded.into_into_dart().into_dart(),
            self.fingerprints_loaded.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::keeper::Snapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::keeper::Snapshot>
    for crate::api::keeper::Snapshot
{
    fn into_into_dart(self) -> crate::api::keeper::Snapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::models::Transport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Usb => 0.into_dart(),
            Self::Nfc => 1.into_dart(),
            Self::Hid => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::models::Transport {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::models::Transport>
    for crate::api::models::Transport
{
    fn into_into_dart(self) -> crate::api::models::Transport {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::models::BioTemplateSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::keeper::Command {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::keeper::CommandKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.value, serializer);
        <String>::sse_encode(self.pin, serializer);
        <String>::sse_encode(self.new_pin, serializer);
        <String>::sse_encode(self.confirm_pin, serializer);
        <bool>::sse_encode(self.confirmed, serializer);
        <String>::sse_encode(self.name, serializer);
    }
}

impl SseEncode for crate::api::keeper::CommandError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.cancelled, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::keeper::CommandKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::keeper::CommandKind::Initialize => 0,
                crate::api::keeper::CommandKind::EnterFingerprints => 1,
                crate::api::keeper::CommandKind::Load => 2,
                crate::api::keeper::CommandKind::Scan => 3,
                crate::api::keeper::CommandKind::Connect => 4,
                crate::api::keeper::CommandKind::Disconnect => 5,
                crate::api::keeper::CommandKind::Hide => 6,
                crate::api::keeper::CommandKind::Unhide => 7,
                crate::api::keeper::CommandKind::ListCredentials => 8,
                crate::api::keeper::CommandKind::DeleteCredential => 9,
                crate::api::keeper::CommandKind::ChangePin => 10,
                crate::api::keeper::CommandKind::ListBio => 11,
                crate::api::keeper::CommandKind::EnrollBio => 12,
                crate::api::keeper::CommandKind::DeleteBio => 13,
                crate::api::keeper::CommandKind::RenameBio => 14,
                crate::api::keeper::CommandKind::Reset => 15,
                crate::api::keeper::CommandKind::Filter => 16,
                crate::api::keeper::CommandKind::Theme => 17,
                crate::api::keeper::CommandKind::Locale => 18,
                crate::api::keeper::CommandKind::Shutdown => 19,
                crate::api::keeper::CommandKind::DynamicColor => 20,
                crate::api::keeper::CommandKind::ColorSeed => 21,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::models::CredentialSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.rp_id, serializer);
        <String>::sse_encode(self.rp_name, serializer);
        <String>::sse_encode(self.user_name, serializer);
        <String>::sse_encode(self.user_display_name, serializer);
    }
}

impl SseEncode for crate::api::models::DeviceSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::models::Transport>::sse_encode(self.transport, serializer);
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.protocol, serializer);
        <bool>::sse_encode(self.credential_management, serializer);
        <bool>::sse_encode(self.pin, serializer);
        <bool>::sse_encode(self.fingerprint, serializer);
    }
}

impl SseEncode for crate::api::models::HiddenAuthenticator {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.label, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::BioTemplateSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::BioTemplateSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::CredentialSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::CredentialSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::DeviceSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::DeviceSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::models::HiddenAuthenticator> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::models::HiddenAuthenticator>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::keeper::OperationInputs {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ask_pin, serializer);
        <bool>::sse_encode(self.change_pin, serializer);
        <bool>::sse_encode(self.requires_confirmation, serializer);
        <bool>::sse_encode(self.touches_hardware, serializer);
        <bool>::sse_encode(self.mutates_device, serializer);
    }
}

impl SseEncode for Option<crate::api::keeper::CommandKind> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::keeper::CommandKind>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::models::DeviceSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::models::DeviceSummary>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::models::Preferences {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.locale, serializer);
        <String>::sse_encode(self.theme, serializer);
        <Vec<crate::api::models::HiddenAuthenticator>>::sse_encode(
            self.hidden_authenticators,
            serializer,
        );
        <bool>::sse_encode(self.dynamic_color, serializer);
        <String>::sse_encode(self.color_seed, serializer);
    }
}

impl SseEncode for crate::api::keeper::Snapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.can_manage_credentials, serializer);
        <bool>::sse_encode(self.can_manage_fingerprints, serializer);
        <Vec<crate::api::models::DeviceSummary>>::sse_encode(self.devices, serializer);
        <Option<crate::api::models::DeviceSummary>>::sse_encode(self.active, serializer);
        <Vec<crate::api::models::CredentialSummary>>::sse_encode(self.credentials, serializer);
        <u64>::sse_encode(self.existing, serializer);
        <u64>::sse_encode(self.remaining, serializer);
        <Vec<crate::api::models::BioTemplateSummary>>::sse_encode(self.templates, serializer);
        <crate::api::models::Preferences>::sse_encode(self.preferences, serializer);
        <String>::sse_encode(self.query, serializer);
        <bool>::sse_encode(self.credentials_loaded, serializer);
        <bool>::sse_encode(self.fingerprints_loaded, serializer);
    }
}

impl SseEncode for crate::api::models::Transport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::models::Transport::Usb => 0,
                crate::api::models::Transport::Nfc => 1,
                crate::api::models::Transport::Hid => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
