// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/keeper.dart';
import 'api/models.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1216109504;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_fidokeeper',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiKeeperCancelEnrollment();

  int crateApiKeeperCloseTimeoutMs({CommandKind? kind});

  List<String> crateApiKeeperColorSeeds();

  String crateApiKeeperDefaultColorSeed();

  Future<Snapshot> crateApiKeeperDispatch({required Command command});

  int crateApiKeeperEnrollCaptured();

  int crateApiKeeperFingerprintNameMaxBytes();

  Future<void> crateApiSimpleInitApp();

  OperationInputs crateApiKeeperOperationInputs({required CommandKind kind});

  Future<Preferences> crateApiModelsPreferencesDefault();

  List<String> crateApiKeeperSupportedLocales();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiKeeperCancelEnrollment() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperCancelEnrollmentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperCancelEnrollmentConstMeta =>
      const TaskConstMeta(debugName: "cancel_enrollment", argNames: []);

  @override
  int crateApiKeeperCloseTimeoutMs({CommandKind? kind}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_command_kind(kind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperCloseTimeoutMsConstMeta,
        argValues: [kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperCloseTimeoutMsConstMeta =>
      const TaskConstMeta(debugName: "close_timeout_ms", argNames: ["kind"]);

  @override
  List<String> crateApiKeeperColorSeeds() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperColorSeedsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperColorSeedsConstMeta =>
      const TaskConstMeta(debugName: "color_seeds", argNames: []);

  @override
  String crateApiKeeperDefaultColorSeed() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperDefaultColorSeedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperDefaultColorSeedConstMeta =>
      const TaskConstMeta(debugName: "default_color_seed", argNames: []);

  @override
  Future<Snapshot> crateApiKeeperDispatch({required Command command}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_command(command, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_snapshot,
          decodeErrorData: sse_decode_command_error,
        ),
        constMeta: kCrateApiKeeperDispatchConstMeta,
        argValues: [command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperDispatchConstMeta =>
      const TaskConstMeta(debugName: "dispatch", argNames: ["command"]);

  @override
  int crateApiKeeperEnrollCaptured() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperEnrollCapturedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperEnrollCapturedConstMeta =>
      const TaskConstMeta(debugName: "enroll_captured", argNames: []);

  @override
  int crateApiKeeperFingerprintNameMaxBytes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperFingerprintNameMaxBytesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperFingerprintNameMaxBytesConstMeta =>
      const TaskConstMeta(
        debugName: "fingerprint_name_max_bytes",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  OperationInputs crateApiKeeperOperationInputs({required CommandKind kind}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_command_kind(kind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_operation_inputs,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperOperationInputsConstMeta,
        argValues: [kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperOperationInputsConstMeta =>
      const TaskConstMeta(debugName: "operation_inputs", argNames: ["kind"]);

  @override
  Future<Preferences> crateApiModelsPreferencesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_preferences,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsPreferencesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsPreferencesDefaultConstMeta =>
      const TaskConstMeta(debugName: "preferences_default", argNames: []);

  @override
  List<String> crateApiKeeperSupportedLocales() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeeperSupportedLocalesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeeperSupportedLocalesConstMeta =>
      const TaskConstMeta(debugName: "supported_locales", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BioTemplateSummary dco_decode_bio_template_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BioTemplateSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Command dco_decode_box_autoadd_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_command(raw);
  }

  @protected
  CommandKind dco_decode_box_autoadd_command_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_command_kind(raw);
  }

  @protected
  DeviceSummary dco_decode_box_autoadd_device_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_device_summary(raw);
  }

  @protected
  Command dco_decode_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Command(
      kind: dco_decode_command_kind(arr[0]),
      value: dco_decode_String(arr[1]),
      pin: dco_decode_String(arr[2]),
      newPin: dco_decode_String(arr[3]),
      confirmPin: dco_decode_String(arr[4]),
      confirmed: dco_decode_bool(arr[5]),
      name: dco_decode_String(arr[6]),
    );
  }

  @protected
  CommandError dco_decode_command_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CommandError(
      cancelled: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  CommandKind dco_decode_command_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CommandKind.values[raw as int];
  }

  @protected
  CredentialSummary dco_decode_credential_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CredentialSummary(
      id: dco_decode_String(arr[0]),
      rpId: dco_decode_String(arr[1]),
      rpName: dco_decode_String(arr[2]),
      userName: dco_decode_String(arr[3]),
      userDisplayName: dco_decode_String(arr[4]),
    );
  }

  @protected
  DeviceSummary dco_decode_device_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DeviceSummary(
      transport: dco_decode_transport(arr[0]),
      path: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
      protocol: dco_decode_String(arr[3]),
      credentialManagement: dco_decode_bool(arr[4]),
      pin: dco_decode_bool(arr[5]),
      fingerprint: dco_decode_bool(arr[6]),
    );
  }

  @protected
  HiddenAuthenticator dco_decode_hidden_authenticator(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HiddenAuthenticator(
      path: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BioTemplateSummary> dco_decode_list_bio_template_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bio_template_summary).toList();
  }

  @protected
  List<CredentialSummary> dco_decode_list_credential_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_credential_summary).toList();
  }

  @protected
  List<DeviceSummary> dco_decode_list_device_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_device_summary).toList();
  }

  @protected
  List<HiddenAuthenticator> dco_decode_list_hidden_authenticator(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_hidden_authenticator).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OperationInputs dco_decode_operation_inputs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OperationInputs(
      askPin: dco_decode_bool(arr[0]),
      changePin: dco_decode_bool(arr[1]),
      requiresConfirmation: dco_decode_bool(arr[2]),
      touchesHardware: dco_decode_bool(arr[3]),
      mutatesDevice: dco_decode_bool(arr[4]),
    );
  }

  @protected
  CommandKind? dco_decode_opt_box_autoadd_command_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_command_kind(raw);
  }

  @protected
  DeviceSummary? dco_decode_opt_box_autoadd_device_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_device_summary(raw);
  }

  @protected
  Preferences dco_decode_preferences(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Preferences(
      locale: dco_decode_String(arr[0]),
      theme: dco_decode_String(arr[1]),
      hiddenAuthenticators: dco_decode_list_hidden_authenticator(arr[2]),
      dynamicColor: dco_decode_bool(arr[3]),
      colorSeed: dco_decode_String(arr[4]),
    );
  }

  @protected
  Snapshot dco_decode_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return Snapshot(
      canManageCredentials: dco_decode_bool(arr[0]),
      canManageFingerprints: dco_decode_bool(arr[1]),
      devices: dco_decode_list_device_summary(arr[2]),
      active: dco_decode_opt_box_autoadd_device_summary(arr[3]),
      credentials: dco_decode_list_credential_summary(arr[4]),
      existing: dco_decode_u_64(arr[5]),
      remaining: dco_decode_u_64(arr[6]),
      templates: dco_decode_list_bio_template_summary(arr[7]),
      preferences: dco_decode_preferences(arr[8]),
      query: dco_decode_String(arr[9]),
      credentialsLoaded: dco_decode_bool(arr[10]),
      fingerprintsLoaded: dco_decode_bool(arr[11]),
    );
  }

  @protected
  Transport dco_decode_transport(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Transport.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BioTemplateSummary sse_decode_bio_template_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return BioTemplateSummary(id: var_id, name: var_name);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Command sse_decode_box_autoadd_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_command(deserializer));
  }

  @protected
  CommandKind sse_decode_box_autoadd_command_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_command_kind(deserializer));
  }

  @protected
  DeviceSummary sse_decode_box_autoadd_device_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_device_summary(deserializer));
  }

  @protected
  Command sse_decode_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_command_kind(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_pin = sse_decode_String(deserializer);
    var var_newPin = sse_decode_String(deserializer);
    var var_confirmPin = sse_decode_String(deserializer);
    var var_confirmed = sse_decode_bool(deserializer);
    var var_name = sse_decode_String(deserializer);
    return Command(
      kind: var_kind,
      value: var_value,
      pin: var_pin,
      newPin: var_newPin,
      confirmPin: var_confirmPin,
      confirmed: var_confirmed,
      name: var_name,
    );
  }

  @protected
  CommandError sse_decode_command_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cancelled = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return CommandError(cancelled: var_cancelled, message: var_message);
  }

  @protected
  CommandKind sse_decode_command_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CommandKind.values[inner];
  }

  @protected
  CredentialSummary sse_decode_credential_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_rpId = sse_decode_String(deserializer);
    var var_rpName = sse_decode_String(deserializer);
    var var_userName = sse_decode_String(deserializer);
    var var_userDisplayName = sse_decode_String(deserializer);
    return CredentialSummary(
      id: var_id,
      rpId: var_rpId,
      rpName: var_rpName,
      userName: var_userName,
      userDisplayName: var_userDisplayName,
    );
  }

  @protected
  DeviceSummary sse_decode_device_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transport = sse_decode_transport(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_credentialManagement = sse_decode_bool(deserializer);
    var var_pin = sse_decode_bool(deserializer);
    var var_fingerprint = sse_decode_bool(deserializer);
    return DeviceSummary(
      transport: var_transport,
      path: var_path,
      label: var_label,
      protocol: var_protocol,
      credentialManagement: var_credentialManagement,
      pin: var_pin,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  HiddenAuthenticator sse_decode_hidden_authenticator(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    return HiddenAuthenticator(path: var_path, label: var_label);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BioTemplateSummary> sse_decode_list_bio_template_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BioTemplateSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bio_template_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<CredentialSummary> sse_decode_list_credential_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CredentialSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_credential_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSummary> sse_decode_list_device_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<HiddenAuthenticator> sse_decode_list_hidden_authenticator(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HiddenAuthenticator>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_hidden_authenticator(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OperationInputs sse_decode_operation_inputs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_askPin = sse_decode_bool(deserializer);
    var var_changePin = sse_decode_bool(deserializer);
    var var_requiresConfirmation = sse_decode_bool(deserializer);
    var var_touchesHardware = sse_decode_bool(deserializer);
    var var_mutatesDevice = sse_decode_bool(deserializer);
    return OperationInputs(
      askPin: var_askPin,
      changePin: var_changePin,
      requiresConfirmation: var_requiresConfirmation,
      touchesHardware: var_touchesHardware,
      mutatesDevice: var_mutatesDevice,
    );
  }

  @protected
  CommandKind? sse_decode_opt_box_autoadd_command_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_command_kind(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DeviceSummary? sse_decode_opt_box_autoadd_device_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_device_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Preferences sse_decode_preferences(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_locale = sse_decode_String(deserializer);
    var var_theme = sse_decode_String(deserializer);
    var var_hiddenAuthenticators = sse_decode_list_hidden_authenticator(
      deserializer,
    );
    var var_dynamicColor = sse_decode_bool(deserializer);
    var var_colorSeed = sse_decode_String(deserializer);
    return Preferences(
      locale: var_locale,
      theme: var_theme,
      hiddenAuthenticators: var_hiddenAuthenticators,
      dynamicColor: var_dynamicColor,
      colorSeed: var_colorSeed,
    );
  }

  @protected
  Snapshot sse_decode_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_canManageCredentials = sse_decode_bool(deserializer);
    var var_canManageFingerprints = sse_decode_bool(deserializer);
    var var_devices = sse_decode_list_device_summary(deserializer);
    var var_active = sse_decode_opt_box_autoadd_device_summary(deserializer);
    var var_credentials = sse_decode_list_credential_summary(deserializer);
    var var_existing = sse_decode_u_64(deserializer);
    var var_remaining = sse_decode_u_64(deserializer);
    var var_templates = sse_decode_list_bio_template_summary(deserializer);
    var var_preferences = sse_decode_preferences(deserializer);
    var var_query = sse_decode_String(deserializer);
    var var_credentialsLoaded = sse_decode_bool(deserializer);
    var var_fingerprintsLoaded = sse_decode_bool(deserializer);
    return Snapshot(
      canManageCredentials: var_canManageCredentials,
      canManageFingerprints: var_canManageFingerprints,
      devices: var_devices,
      active: var_active,
      credentials: var_credentials,
      existing: var_existing,
      remaining: var_remaining,
      templates: var_templates,
      preferences: var_preferences,
      query: var_query,
      credentialsLoaded: var_credentialsLoaded,
      fingerprintsLoaded: var_fingerprintsLoaded,
    );
  }

  @protected
  Transport sse_decode_transport(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Transport.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bio_template_summary(
    BioTemplateSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_command_kind(
    CommandKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command_kind(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_device_summary(
    DeviceSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_summary(self, serializer);
  }

  @protected
  void sse_encode_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command_kind(self.kind, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_String(self.pin, serializer);
    sse_encode_String(self.newPin, serializer);
    sse_encode_String(self.confirmPin, serializer);
    sse_encode_bool(self.confirmed, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_command_error(CommandError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.cancelled, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_command_kind(CommandKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_credential_summary(
    CredentialSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.rpId, serializer);
    sse_encode_String(self.rpName, serializer);
    sse_encode_String(self.userName, serializer);
    sse_encode_String(self.userDisplayName, serializer);
  }

  @protected
  void sse_encode_device_summary(DeviceSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transport(self.transport, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_bool(self.credentialManagement, serializer);
    sse_encode_bool(self.pin, serializer);
    sse_encode_bool(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_hidden_authenticator(
    HiddenAuthenticator self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bio_template_summary(
    List<BioTemplateSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bio_template_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_credential_summary(
    List<CredentialSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_credential_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_summary(
    List<DeviceSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_hidden_authenticator(
    List<HiddenAuthenticator> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_hidden_authenticator(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_operation_inputs(
    OperationInputs self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.askPin, serializer);
    sse_encode_bool(self.changePin, serializer);
    sse_encode_bool(self.requiresConfirmation, serializer);
    sse_encode_bool(self.touchesHardware, serializer);
    sse_encode_bool(self.mutatesDevice, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_command_kind(
    CommandKind? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_command_kind(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_device_summary(
    DeviceSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_device_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_preferences(Preferences self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.locale, serializer);
    sse_encode_String(self.theme, serializer);
    sse_encode_list_hidden_authenticator(self.hiddenAuthenticators, serializer);
    sse_encode_bool(self.dynamicColor, serializer);
    sse_encode_String(self.colorSeed, serializer);
  }

  @protected
  void sse_encode_snapshot(Snapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.canManageCredentials, serializer);
    sse_encode_bool(self.canManageFingerprints, serializer);
    sse_encode_list_device_summary(self.devices, serializer);
    sse_encode_opt_box_autoadd_device_summary(self.active, serializer);
    sse_encode_list_credential_summary(self.credentials, serializer);
    sse_encode_u_64(self.existing, serializer);
    sse_encode_u_64(self.remaining, serializer);
    sse_encode_list_bio_template_summary(self.templates, serializer);
    sse_encode_preferences(self.preferences, serializer);
    sse_encode_String(self.query, serializer);
    sse_encode_bool(self.credentialsLoaded, serializer);
    sse_encode_bool(self.fingerprintsLoaded, serializer);
  }

  @protected
  void sse_encode_transport(Transport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
