// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active`, `apply`, `cancel_requested`, `disconnect`, `new`, `scan`, `session_pin`, `snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `State`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

OperationInputs operationInputs({required CommandKind kind}) =>
    RustLib.instance.api.crateApiKeeperOperationInputs(kind: kind);

/// 写操作等待当前这次设备调用结束；读取类超时后可以先退出，句柄随进程回收。
int closeTimeoutMs({CommandKind? kind}) =>
    RustLib.instance.api.crateApiKeeperCloseTimeoutMs(kind: kind);

List<String> colorSeeds() => RustLib.instance.api.crateApiKeeperColorSeeds();

String defaultColorSeed() =>
    RustLib.instance.api.crateApiKeeperDefaultColorSeed();

List<String> supportedLocales() =>
    RustLib.instance.api.crateApiKeeperSupportedLocales();

int fingerprintNameMaxBytes() =>
    RustLib.instance.api.crateApiKeeperFingerprintNameMaxBytes();

int enrollCaptured() => RustLib.instance.api.crateApiKeeperEnrollCaptured();

bool cancelEnrollment() =>
    RustLib.instance.api.crateApiKeeperCancelEnrollment();

Future<Snapshot> dispatch({required Command command}) =>
    RustLib.instance.api.crateApiKeeperDispatch(command: command);

class Command {
  final CommandKind kind;
  final String value;
  final String pin;
  final String newPin;
  final String confirmPin;
  final bool confirmed;

  /// 指纹新名称。和 PIN 分开，避免调用方把名称写进 PIN 字段。
  final String name;

  const Command({
    required this.kind,
    required this.value,
    required this.pin,
    required this.newPin,
    required this.confirmPin,
    required this.confirmed,
    required this.name,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      value.hashCode ^
      pin.hashCode ^
      newPin.hashCode ^
      confirmPin.hashCode ^
      confirmed.hashCode ^
      name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Command &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value &&
          pin == other.pin &&
          newPin == other.newPin &&
          confirmPin == other.confirmPin &&
          confirmed == other.confirmed &&
          name == other.name;
}

class CommandError implements FrbException {
  final bool cancelled;
  final String message;

  const CommandError({required this.cancelled, required this.message});

  @override
  int get hashCode => cancelled.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandError &&
          runtimeType == other.runtimeType &&
          cancelled == other.cancelled &&
          message == other.message;
}

enum CommandKind {
  initialize,
  enterFingerprints,
  load,
  scan,
  connect,
  disconnect,
  hide_,
  unhide,
  listCredentials,
  deleteCredential,
  changePin,
  listBio,
  enrollBio,
  deleteBio,
  renameBio,
  reset,
  filter,
  theme,
  locale,
  shutdown,
  dynamicColor,
  colorSeed,
}

class OperationInputs {
  final bool askPin;
  final bool changePin;
  final bool requiresConfirmation;

  /// 会打开设备。界面用它占用忙碌状态；筛选和偏好设置不占。
  final bool touchesHardware;

  /// 会改设备内容。关闭时要等满一次设备 I/O，避免写到一半进程退出。
  final bool mutatesDevice;

  const OperationInputs({
    required this.askPin,
    required this.changePin,
    required this.requiresConfirmation,
    required this.touchesHardware,
    required this.mutatesDevice,
  });

  @override
  int get hashCode =>
      askPin.hashCode ^
      changePin.hashCode ^
      requiresConfirmation.hashCode ^
      touchesHardware.hashCode ^
      mutatesDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationInputs &&
          runtimeType == other.runtimeType &&
          askPin == other.askPin &&
          changePin == other.changePin &&
          requiresConfirmation == other.requiresConfirmation &&
          touchesHardware == other.touchesHardware &&
          mutatesDevice == other.mutatesDevice;
}

class Snapshot {
  final bool canManageCredentials;
  final bool canManageFingerprints;
  final List<DeviceSummary> devices;
  final DeviceSummary? active;
  final List<CredentialSummary> credentials;
  final BigInt existing;
  final BigInt remaining;
  final List<BioTemplateSummary> templates;
  final Preferences preferences;
  final String query;
  final bool credentialsLoaded;
  final bool fingerprintsLoaded;

  const Snapshot({
    required this.canManageCredentials,
    required this.canManageFingerprints,
    required this.devices,
    this.active,
    required this.credentials,
    required this.existing,
    required this.remaining,
    required this.templates,
    required this.preferences,
    required this.query,
    required this.credentialsLoaded,
    required this.fingerprintsLoaded,
  });

  @override
  int get hashCode =>
      canManageCredentials.hashCode ^
      canManageFingerprints.hashCode ^
      devices.hashCode ^
      active.hashCode ^
      credentials.hashCode ^
      existing.hashCode ^
      remaining.hashCode ^
      templates.hashCode ^
      preferences.hashCode ^
      query.hashCode ^
      credentialsLoaded.hashCode ^
      fingerprintsLoaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Snapshot &&
          runtimeType == other.runtimeType &&
          canManageCredentials == other.canManageCredentials &&
          canManageFingerprints == other.canManageFingerprints &&
          devices == other.devices &&
          active == other.active &&
          credentials == other.credentials &&
          existing == other.existing &&
          remaining == other.remaining &&
          templates == other.templates &&
          preferences == other.preferences &&
          query == other.query &&
          credentialsLoaded == other.credentialsLoaded &&
          fingerprintsLoaded == other.fingerprintsLoaded;
}
