// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active`, `apply`, `disconnect`, `new`, `snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `State`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`

Future<Snapshot> dispatch({required Command command}) =>
    RustLib.instance.api.crateApiKeeperDispatch(command: command);

class Command {
  final CommandKind kind;
  final String value;
  final String pin;
  final String newPin;
  final String confirmPin;
  final bool confirmed;

  const Command({
    required this.kind,
    required this.value,
    required this.pin,
    required this.newPin,
    required this.confirmPin,
    required this.confirmed,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      value.hashCode ^
      pin.hashCode ^
      newPin.hashCode ^
      confirmPin.hashCode ^
      confirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Command &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value &&
          pin == other.pin &&
          newPin == other.newPin &&
          confirmPin == other.confirmPin &&
          confirmed == other.confirmed;
}

enum CommandKind {
  load,
  scan,
  connect,
  disconnect,
  hide_,
  unhide,
  listCredentials,
  deleteCredential,
  changePin,
  listBio,
  enrollBio,
  deleteBio,
  reset,
  filter,
  theme,
  locale,
  shutdown,
}

class Snapshot {
  final List<DeviceSummary> devices;
  final DeviceSummary? active;
  final List<CredentialSummary> credentials;
  final BigInt existing;
  final BigInt remaining;
  final List<BioTemplateSummary> templates;
  final Preferences preferences;
  final String query;

  const Snapshot({
    required this.devices,
    this.active,
    required this.credentials,
    required this.existing,
    required this.remaining,
    required this.templates,
    required this.preferences,
    required this.query,
  });

  @override
  int get hashCode =>
      devices.hashCode ^
      active.hashCode ^
      credentials.hashCode ^
      existing.hashCode ^
      remaining.hashCode ^
      templates.hashCode ^
      preferences.hashCode ^
      query.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Snapshot &&
          runtimeType == other.runtimeType &&
          devices == other.devices &&
          active == other.active &&
          credentials == other.credentials &&
          existing == other.existing &&
          remaining == other.remaining &&
          templates == other.templates &&
          preferences == other.preferences &&
          query == other.query;
}
