// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BioTemplateSummary {
  final String id;
  final String name;

  const BioTemplateSummary({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BioTemplateSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class CredentialSummary {
  final String id;
  final String rpId;
  final String rpName;
  final String userName;
  final String userDisplayName;

  const CredentialSummary({
    required this.id,
    required this.rpId,
    required this.rpName,
    required this.userName,
    required this.userDisplayName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rpId.hashCode ^
      rpName.hashCode ^
      userName.hashCode ^
      userDisplayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CredentialSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rpId == other.rpId &&
          rpName == other.rpName &&
          userName == other.userName &&
          userDisplayName == other.userDisplayName;
}

class DeviceSummary {
  final String path;
  final String label;
  final String protocol;
  final bool credentialManagement;
  final bool pin;
  final bool fingerprint;

  const DeviceSummary({
    required this.path,
    required this.label,
    required this.protocol,
    required this.credentialManagement,
    required this.pin,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      label.hashCode ^
      protocol.hashCode ^
      credentialManagement.hashCode ^
      pin.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSummary &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          label == other.label &&
          protocol == other.protocol &&
          credentialManagement == other.credentialManagement &&
          pin == other.pin &&
          fingerprint == other.fingerprint;
}

class HiddenAuthenticator {
  final String path;
  final String label;

  const HiddenAuthenticator({required this.path, required this.label});

  @override
  int get hashCode => path.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HiddenAuthenticator &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          label == other.label;
}

class Preferences {
  final String locale;
  final String theme;
  final List<HiddenAuthenticator> hiddenAuthenticators;

  const Preferences({
    required this.locale,
    required this.theme,
    required this.hiddenAuthenticators,
  });

  static Future<Preferences> default_() =>
      RustLib.instance.api.crateApiModelsPreferencesDefault();

  @override
  int get hashCode =>
      locale.hashCode ^ theme.hashCode ^ hiddenAuthenticators.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Preferences &&
          runtimeType == other.runtimeType &&
          locale == other.locale &&
          theme == other.theme &&
          hiddenAuthenticators == other.hiddenAuthenticators;
}
