set(FIDOKEEPER_DLL_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../dll/1.17.0-v143")

function(fidokeeper_runtime_files output target)
  if(target STREQUAL "windows-x64")
    set(architecture "amd64")
  elseif(target STREQUAL "windows-x86")
    set(architecture "x86")
  elseif(target STREQUAL "windows-arm64")
    set(architecture "arm64")
  elseif(target STREQUAL "windows-arm")
    set(architecture "arm")
  else()
    message(FATAL_ERROR "未知 FIDO DLL 目标架构：${target}")
  endif()
  set(runtime_files)
  foreach(name fido2.dll cbor.dll crypto-56.dll zlib1.dll)
    set(path "${FIDOKEEPER_DLL_ROOT}/${architecture}/${name}")
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "缺少 ${target} 运行库：${path}，不能混用其他架构的 DLL")
    endif()
    list(APPEND runtime_files "${path}")
  endforeach()
  set(${output} "${runtime_files}" PARENT_SCOPE)
endfunction()
